### ISSUE TITLE
/ftc create txt Test not work 

### ISSUE THREAD

**Issue by MadooxMc** [Vecnavium/FloatingTextCreator#1]
Help

**Comment by Vecnavium** [comment]
Hi, the reason why it's not working is because you are likely not using the texts from config.yml. You have to refer to the config.yml file and from there you run /ftc create txt WelcomeText for example or any text you want and create, be sure you read README.md HowToUse

**Comment by MadooxMc** [comment]
I use the text from config.yml but not work

**Comment by Vecnavium** [comment]
Could send a file of the config.yml here?

**Comment by MadooxMc** [comment]
[config.txt](https://github.com/Vecnavium/FloatingTextCreator/files/6953715/config.txt)
is the confyg original but i move to txt to send you

**Comment by Vecnavium** [comment]
Yeah your not doing it right

ft-texts:
  WelcomeText:
    - "Hello {player} welcome to the server!"
    - "Test"
  RandomText:
    - "Hello world! 1"
    - "Hello world! 2"
    
You would need to run /ftc create txt {txtname} without { } and txtname is the text title above the messages/texts for the floatingtext

**Comment by MadooxMc** [comment]
Ok but why /ftc create txt Test not work, if i understand, the textname is: 
WelcomeText:
- "Hello {player} welcome to the server!"
- "Test"
RandomText:
- "Hello world! 1"
- "Hello world! 2"
but anything work, no Hello world! 1
not Test

**Comment by Vecnavium** [comment]
Replace Test with WelcomeText or RandomText because you dont have a text title specifically named Test to do that

**Comment by MadooxMc** [comment]
Ok is good for me thank you very much for your help !
