### ISSUE TITLE
Bug in multiworld

### ISSUE THREAD

**Issue by rokibot009** [Vecnavium/FloatingTextCreator#5]
the plugin is working but there is a bug issue in multiworld..

Can u fix it?
btw.. ur plugin is cool

**Comment by Vecnavium** [comment]
Closing this issue.
Please respond to the issue template so it's more detailed so I know why the issue is created and what the issue is, and I doubt this is a FloatingTextCreator issue it's more than likely MultiWorld or another plugin causing this
